# fly.toml app configuration file generated for prueba-final-jenkins-ci-cd-fly-io on 2024-10-22T19:20:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prueba-final-jenkins-ci-cd-fly-io'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
